repos:
- repo: local
  hooks:
    # flake8
    - id: flake8
      name: flake8
      entry: poetry run flake8
      language: system
      types_or: [python, pyi]
      require_serial: true

    # mypy
    - id: black
      name: black
      entry: poetry run black
      language: system
      types_or: [python, pyi]
      require_serial: true

    # isort 
    - id: isort
      name: isort
      entry: poetry run isort
      language: system
      types_or: [python, pyi]
      require_serial: true